x-app: &app
  build:
    context: .
  image: kozenii-app:0.1.0
  stdin_open: true
  tty: true
  volumes:
    - ${APP_ROOT:-.}:/app:cached
    - bundle:/bundle
    - history:/usr/local/hist
  environment:
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
    HISTFILE: /usr/local/hist/.bash_history
    MYSQL_HISTFILE: /usr/local/hist/.mysql_history
    IRB_HISTFILE: /usr/local/hist/.irb_history
    MYSQL_PORT_3306_TCP_ADDR: mysql
    # REDIS_PORT_6379_TCP_ADDR: redis
    DEV_DB_PASSWORD: root

  depends_on:
    mysql:
      condition: service_healthy
    # redis:
    #   condition: service_healthy

  tmpfs:
    - /tmp


services:
  sh:
    <<: *app
    command: /bin/bash

  web:
    <<: *app
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"


  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # redis:
  #   image: redis:6
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: redis-cli ping
  #     interval: 1s
  #     timeout: 3s
  #     retries: 30

volumes:
  bundle:
  history:
  mysql:
